"""
Django settings for swrs_config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-04m+tt07=h7pe$g@7-cst*a4o*$q^myb6cvinqtsbmjyo&tqo1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow only localhost and a single LAN IP for access from one Wi‑Fi network
# Replace '192.168.100.9' below with the machine's current LAN IP if different
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.100.9',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'presence_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swrs_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'presence_app.context_processors.is_instructor',
            ],
        },
    },
]

WSGI_APPLICATION = 'swrs_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE CONFIGURATION
# ----------------------
# By default we use SQLite for local development.  To switch to MySQL,
# install the client driver (e.g. `pip install mysqlclient`) and create a
# database/user in your MySQL server (you can do this with MySQL Workbench).
#
# Example SQL:
#
#   CREATE DATABASE swrs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
#   CREATE USER 'swrs_user'@'localhost' IDENTIFIED BY 'strongpassword';
#   GRANT ALL PRIVILEGES ON swrs.* TO 'swrs_user'@'localhost';
#   FLUSH PRIVILEGES;
#
# Then configure the DATABASES setting below.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cisproximity',         
        'USER': 'root',                
        'PASSWORD': 'Password',    
        'HOST': '127.0.0.1',           
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password validation
# We relax the default Django rules to make the registration form
# less sensitive to usernames and allow shorter/less-complex passwords.
# The similarity and numeric validators have been removed; a smaller
# minimum length is enforced instead.
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #     # don't compare against email address
    #     'OPTIONS': {
    #         'user_attributes': ('username', 'first_name', 'last_name'),
    #     }
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
    # numeric-only validator removed to allow passwords like "12345abc" etc.
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'presence_app' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CSRF & Security
# Only trust local dev origins
# CSRF trusted origins for local dev and ngrok (used for remote testing)
# CSRF trusted origins restricted to local dev and the specific LAN IP
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.100.9:8000',
]

# Allow CSRF for development - cookies from same network
CSRF_COOKIE_SECURE = False  # Allow HTTP in development
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access if needed
SESSION_COOKIE_SECURE = False  # Allow HTTP in development
SESSION_COOKIE_HTTPONLY = True  # Keep sessions server-side safe

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# CIS-Prox Configuration: Authorized Campus Wi-Fi Subnets
# Add all campus network subnets here (CIDR notation)
CAMPUS_WIFI_SUBNETS = []