# Generated by Django 4.2.7 on 2026-01-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('section', models.CharField(max_length=10)),
                ('program', models.CharField(choices=[('GENERAL', 'General'), ('SMP', 'Service Management Program'), ('BA', 'Business Administration')], default='GENERAL', max_length=20)),
            ],
            options={
                'ordering': ['year', 'section'],
                'unique_together': {('year', 'section', 'program')},
            },
        ),
        migrations.AddField(
            model_name='studentpresence',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence_app.section'),
        ),
    ]
