# Generated by Django 4.2.7 on 2026-01-29 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence_app', '0002_section_studentpresence_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_app.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CLUB', 'Club Activity'), ('VOLUNTEER', 'Volunteer Work'), ('SEMINAR', 'Seminar/Workshop'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural Event'), ('OTHER', 'Other')], max_length=20)),
                ('activity_name', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('activity_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='FlagRaisingCeremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frc_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('student', 'attendance_date')},
            },
        ),
    ]
