# Generated by Django 4.2.7 on 2026-01-29 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0003_userprofile_checkinrecord_activityhour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhour',
            options={'ordering': ['-sign_in_time']},
        ),
        migrations.RemoveField(
            model_name='activityhour',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activityhour',
            name='hours',
        ),
        migrations.AddField(
            model_name='activityhour',
            name='sign_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activityhour',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
