# Generated by Django 4.2.7 on 2026-01-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0004_alter_activityhour_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityhour',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='activityhour',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activityhour',
            name='description',
        ),
    ]
