# Generated by Django 4.2.7 on 2026-02-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence_app', '0006_instructorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_verified', models.BooleanField(default=True, help_text='IP is on authorized campus subnet')),
                ('signed_in_at', models.DateTimeField(auto_now_add=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence_app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_in_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='presence_ap_user_id_f3aa2a_idx'), models.Index(fields=['is_active', '-signed_in_at'], name='presence_ap_is_acti_536da1_idx')],
            },
        ),
    ]
