# Generated by Django 4.2.7 on 2026-02-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence_app', '0007_presencesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField(auto_now_add=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence_app.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_in_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sign_in_time'],
            },
        ),
        migrations.DeleteModel(
            name='CheckInRecord',
        ),
    ]
