# Generated by Django 4.2.7 on 2026-02-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence_app', '0008_signinrecord_delete_checkinrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='How long student was in lab')),
                ('room', models.ForeignKey(blank=True, help_text='Lab room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence_app.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Exit Record',
                'verbose_name_plural': 'Laboratory History',
                'ordering': ['-exit_time'],
            },
        ),
    ]
