# Generated by Django 4.2.7 on 2026-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0009_laboratoryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyLaboratoryHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lab_room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presence_app_laboratoryhistory',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID in format XXX-XXXX-X', max_length=11, null=True),
        ),
    ]
