# Generated by Django 4.2.7 on 2026-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0010_legacylaboratoryhistory_userprofile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id_number',
            field=models.CharField(blank=True, help_text='Format: XXX-XXXX-X (8 digits total)', max_length=12),
        ),
    ]
