# Generated by Django 4.2.7 on 2026-02-10 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence_app', '0011_remove_userprofile_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_level',
            field=models.CharField(choices=[('PUBLIC', 'Everyone'), ('FRIENDS_ONLY', 'Connected users'), ('ONLY_ME', 'Only me')], default='PUBLIC', max_length=20),
        ),
    ]
