# Generated by Django 4.2.7 on 2026-03-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0014_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_room',
            field=models.ForeignKey(blank=True, help_text='The room assigned to the instructor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='presence_app.room'),
        ),
    ]
