# Generated by Django 6.0.3 on 2026-03-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_app', '0015_instructorprofile_instructor_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instructor_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('none', 'None')], default='everyone', help_text='Determines if instructor is visible in instructor search results', max_length=20),
        ),
    ]
